#!/usr/bin/env node
/**
 * Encrypts photos/ and script.js with AES-256-GCM (PBKDF2 key).
 * Output: data.enc.js  — commit this to the repo.
 * Gitignore: photos/ script.js  — never go to git.
 *
 * Usage:  node encrypt.js
 */
const { webcrypto } = require('crypto');
const subtle = webcrypto.subtle;
const getRandomValues = buf => webcrypto.getRandomValues(buf);
const fs   = require('fs');
const path = require('path');
const rl   = require('readline').createInterface({ input: process.stdin, output: process.stdout });

const PHOTOS_DIR  = './photos';
const OUTPUT_FILE = './data.enc.js';
const ITERATIONS  = 250_000;

const toB64 = buf => Buffer.from(buf).toString('base64');

function ask(q) {
  return new Promise(r => rl.question(q, a => { rl.close(); r(a.trim()); }));
}

async function deriveKey(password, salt) {
  const raw = await subtle.importKey(
    'raw', Buffer.from(password, 'utf8'), 'PBKDF2', false, ['deriveKey']
  );
  return subtle.deriveKey(
    { name: 'PBKDF2', salt, iterations: ITERATIONS, hash: 'SHA-256' },
    raw,
    { name: 'AES-GCM', length: 256 },
    false,
    ['encrypt']
  );
}

async function encryptBuf(key, buf) {
  const iv = getRandomValues(new Uint8Array(12));
  const ct = await subtle.encrypt({ name: 'AES-GCM', iv }, key, buf);
  return { iv: toB64(iv), data: toB64(ct) };
}

async function main() {
  const password = await ask('Encryption password: ');
  if (!password) { console.error('Password cannot be empty.'); process.exit(1); }

  const confirm = await new Promise(r => {
    const r2 = require('readline').createInterface({ input: process.stdin, output: process.stdout });
    r2.question('Confirm password: ', a => { r2.close(); r(a.trim()); });
  });
  if (password !== confirm) { console.error('Passwords do not match.'); process.exit(1); }

  const salt = getRandomValues(new Uint8Array(16));
  const key  = await deriveKey(password, salt);

  /* Encrypt photos */
  const exts  = /\.(jpe?g|png|gif|webp)$/i;
  const files = fs.readdirSync(PHOTOS_DIR).filter(f => exts.test(f));
  if (!files.length) { console.error(`No images found in ${PHOTOS_DIR}/`); process.exit(1); }

  console.log(`\nEncrypting ${files.length} photos...`);
  const photos = {};
  for (const file of files) {
    photos[file] = await encryptBuf(key, fs.readFileSync(path.join(PHOTOS_DIR, file)));
    console.log(`  ✓ ${file}`);
  }

  /* Encrypt script.js */
  if (!fs.existsSync('./script.js')) { console.error('script.js not found.'); process.exit(1); }
  console.log('\nEncrypting script.js...');
  const scripts = {
    'script.js': await encryptBuf(key, Buffer.from(fs.readFileSync('./script.js', 'utf8'), 'utf8')),
  };
  console.log('  ✓ script.js');

  const payload = JSON.stringify({ salt: toB64(salt), photos, scripts });
  const out = `/* Auto-generated by encrypt.js — do not edit manually */\nconst ENC=${payload};`;
  fs.writeFileSync(OUTPUT_FILE, out, 'utf8');
  console.log(`\nDone → ${OUTPUT_FILE}`);
  console.log('Next steps:');
  console.log('  1. git add data.enc.js && git commit');
  console.log('  2. Make sure photos/ and script.js are in .gitignore (already done)');
}

main().catch(e => { console.error(e.message); process.exit(1); });
