#!/usr/bin/env node
/**
 * Compresses photos, then encrypts photos/ and script.js with AES-256-GCM.
 * Output: data.enc.js  — commit this to the repo.
 * Gitignore: photos/ script.js  — never go to git.
 *
 * Usage:  npm install sharp && node encrypt.js
 */
const { webcrypto } = require('crypto');
const subtle = webcrypto.subtle;
const getRandomValues = buf => webcrypto.getRandomValues(buf);
const fs   = require('fs');
const path = require('path');
const rl   = require('readline').createInterface({ input: process.stdin, output: process.stdout });
let sharp;
try { sharp = require('sharp'); } catch { sharp = null; }

const PHOTOS_DIR  = './photos';
const OUTPUT_FILE = './data.enc.js';
const ITERATIONS  = 100_000;
const MAX_PX      = 1920;
const QUALITY     = 82;

/* Explicit extra rotation (degrees) for specific files, on top of EXIF auto-rotate */
const EXTRA_ROTATE = {
  'we.jpeg':  90,
  'we1.jpeg': 90,
};

const toB64 = buf => Buffer.from(buf).toString('base64');

function ask(q) {
  return new Promise(r => rl.question(q, a => { rl.close(); r(a.trim()); }));
}

async function deriveKey(password, salt) {
  const raw = await subtle.importKey(
    'raw', Buffer.from(password, 'utf8'), 'PBKDF2', false, ['deriveKey']
  );
  return subtle.deriveKey(
    { name: 'PBKDF2', salt, iterations: ITERATIONS, hash: 'SHA-256' },
    raw,
    { name: 'AES-GCM', length: 256 },
    false,
    ['encrypt']
  );
}

async function encryptBuf(key, buf) {
  const iv = getRandomValues(new Uint8Array(12));
  const ct = await subtle.encrypt({ name: 'AES-GCM', iv }, key, buf);
  return { iv: toB64(iv), data: toB64(ct) };
}

async function readPhoto(filePath) {
  if (!sharp) return fs.readFileSync(filePath);
  const orig     = fs.statSync(filePath).size;
  const filename = path.basename(filePath);
  const extra    = EXTRA_ROTATE[filename] || 0;
  let pipeline = sharp(filePath).rotate(); /* auto-apply EXIF orientation */
  if (extra) pipeline = pipeline.rotate(extra);
  const buf = await pipeline
    .resize(MAX_PX, MAX_PX, { fit: 'inside', withoutEnlargement: true })
    .jpeg({ quality: QUALITY, mozjpeg: true })
    .toBuffer();
  const pct = Math.round((1 - buf.length / orig) * 100);
  process.stdout.write(` (${(orig/1024/1024).toFixed(1)}MB → ${(buf.length/1024/1024).toFixed(1)}MB, -${pct}%)`);
  return buf;
}

async function main() {
  if (!sharp) console.warn('⚠ sharp not installed — photos will not be compressed. Run: npm install sharp\n');

  const password = await ask('Encryption password: ');
  if (!password) { console.error('Password cannot be empty.'); process.exit(1); }

  const confirm = await new Promise(r => {
    const r2 = require('readline').createInterface({ input: process.stdin, output: process.stdout });
    r2.question('Confirm password: ', a => { r2.close(); r(a.trim()); });
  });
  if (password !== confirm) { console.error('Passwords do not match.'); process.exit(1); }

  const salt = getRandomValues(new Uint8Array(16));
  const key  = await deriveKey(password, salt);

  /* Compress + encrypt photos */
  const exts  = /\.(jpe?g|png|gif|webp)$/i;
  const files = fs.readdirSync(PHOTOS_DIR).filter(f => exts.test(f));
  if (!files.length) { console.error(`No images found in ${PHOTOS_DIR}/`); process.exit(1); }

  console.log(`\nEncrypting ${files.length} photos...`);
  const photos = {};
  for (const file of files) {
    process.stdout.write(`  ✓ ${file}`);
    const buf = await readPhoto(path.join(PHOTOS_DIR, file));
    photos[file] = await encryptBuf(key, buf);
    process.stdout.write('\n');
  }

  /* Encrypt script.js */
  if (!fs.existsSync('./script.js')) { console.error('script.js not found.'); process.exit(1); }
  console.log('\nEncrypting script.js...');
  const scripts = {
    'script.js': await encryptBuf(key, Buffer.from(fs.readFileSync('./script.js', 'utf8'), 'utf8')),
  };
  console.log('  ✓ script.js');

  const payload = JSON.stringify({ salt: toB64(salt), photos, scripts });
  const out = `/* Auto-generated by encrypt.js — do not edit manually */\nconst ENC=${payload};`;
  fs.writeFileSync(OUTPUT_FILE, out, 'utf8');

  const sizeMB = (fs.statSync(OUTPUT_FILE).size / 1024 / 1024).toFixed(1);
  console.log(`\nDone → ${OUTPUT_FILE} (${sizeMB}MB)`);
}

main().catch(e => { console.error(e.message); process.exit(1); });
